ttf-malayalam/AnjaliOldLipi.ttf usr/share/fonts/truetype/ttf-malayalam-fonts/
ttf-malayalam/Dyuthi3.ttf usr/share/fonts/truetype/ttf-malayalam-fonts/
ttf-malayalam/Kalyani121.ttf usr/share/fonts/truetype/ttf-malayalam-fonts/
ttf-malayalam/lohit_ml.ttf usr/share/fonts/truetype/ttf-malayalam-fonts/
ttf-malayalam/RaghuMalayalamSans2.ttf usr/share/fonts/truetype/ttf-malayalam-fonts/
ttf-malayalam/suruma2.ttf usr/share/fonts/truetype/ttf-malayalam-fonts/
