ttf-tamil/TAMu_Kadampari.ttf usr/share/fonts/truetype/ttf-tamil-fonts/
ttf-tamil/TAMu_Kalyani.ttf usr/share/fonts/truetype/ttf-tamil-fonts/
ttf-tamil/TAMu_Maduram.ttf usr/share/fonts/truetype/ttf-tamil-fonts/
ttf-tamil/TSCu_Comic.ttf usr/share/fonts/truetype/ttf-tamil-fonts/
ttf-tamil/TSCu_paranarb.ttf usr/share/fonts/truetype/ttf-tamil-fonts/
ttf-tamil/TSCu_paranari.ttf usr/share/fonts/truetype/ttf-tamil-fonts/
ttf-tamil/TSCu_Paranar.ttf usr/share/fonts/truetype/ttf-tamil-fonts/
ttf-tamil/TSCu_Times.ttf usr/share/fonts/truetype/ttf-tamil-fonts/
